/* All text, links and data live in this file. */
window.CONTENT = {
  person: {
    name: "Adya Srivastava",
    role: "BITS Pilani, EEE · ML research and engineering",
    intro: [
      "I'm Adya, a BITS Pilani graduate in Electrical and Electronics Engineering (EEE). I genuinely enjoy building things from scratch and figuring out how they work along the way. I'm especially interested in AI and ML, but what keeps me excited is the engineering and research around them: taking a vague question, digging into it, experimenting, breaking things, and eventually turning an idea into something that actually works. I love learning by building, and I'm constantly trying to go one level deeper than what I already know.",
      "I'm currently looking for opportunities where I can work closely with interesting problems in AI/ML, research, and engineering. But I'm also here because I like talking to people who are building, experimenting, and thinking about the same things. If you're working on something interesting, have a different way of looking at AI/ML, have recently discovered something that changed how you think about the field, or simply have a few things you think I should know, I'd genuinely love to hear from you. I'm always up for a good conversation."
    ],
    openTo: ["ML research and engineering roles", "Hackathon teammates", "Resources you think I should read", "Conversations about AI/ML"],
    proof: ["4 research papers", "National winner, Citi Innovation Challenge", "Open source on GitHub"],
    closingTitle: "At the core, I like making things.",
    closing: [
      "I like starting with a blank page, learning whatever I need to learn, and slowly turning an idea into something real. Research gives me the opportunity to chase questions that don't have obvious answers, while engineering gives me the satisfaction of actually building the answer. AI and ML happen to sit at a particularly exciting intersection of the two for me.",
      "I don't think of learning as something that ends when you understand the theory. I want to understand enough to build with it, break it, question it, and hopefully discover something that wasn't obvious before. That's probably what keeps me moving between research papers, experiments, systems, and completely new things I know very little about. There's always something more to uncover, and that's the part I enjoy most."
    ]
  },

  links: {
    github: "https://github.com/Adya6714",
    linkedin: "https://www.linkedin.com/in/adyasri",
    openreview: "https://openreview.net/forum?id=d8w4gMVQ1w",
    kaggle: "https://www.kaggle.com/adyasrivastava",
    youtube: "https://www.youtube.com/@adyasrivastava9398",
    twitter: "https://x.com/adyasrivastava2",
    meraki: "https://srivastavadya.wixsite.com/meraki14",
    email: "srivastavadya@gmail.com",
    resume: "assets/Resume_Adya_Srivastava.pdf"
  },

  areas: [
    { id: "reasoning", kind: "Research", title: "How models reason", line: "Do they work a problem out, or recall something similar?", go: "research", color: "#72f1df" },
    { id: "vision", kind: "Research", title: "Vision and documents", line: "Does a model's confidence come from what it actually sees?", go: "research", color: "#b9a6ff" },
    { id: "production", kind: "Engineering", title: "Production ML", line: "Speech AI at Nurix: a voicemail detector and 40% fewer transcription errors.", go: "path", color: "#6fd4c8" },
    { id: "systems", kind: "Engineering", title: "AI systems and agents", line: "OmniMesh offline triage, FraudScope360 (Citi national winner), FraudSense.", go: "projects", color: "#8fd0ff" }
  ],

  research: [
    { id: "r-reasoning", tag: "Reasoning", status: "CAISc 2026", color: "amber",
      title: "Same Score, Different Strategy",
      question: "When two AI models get the same score, are they solving problems the same way?",
      what: "Tells whether an AI model solved a problem or remembered it.",
      big: "1.00 to 0.00", caption: "o3-mini's score on a scheduling task after a simple rename",
      did: "Built three probes (rename and rewording, plan versus execution, closeness to training data) and ran 219 problems across arithmetic, planning and optimisation on five frontier models, about 20,000 API calls, with exact answer checkers.",
      found: ["Models with matching scores break in very different ways.", "Accepting an injected wrong step 88 to 100% of the time did not predict whether a model finished correctly.", "Even with three probes, 61.6% of problems resist a clean label, so behaviour alone is not enough."],
      next: "Look inside the models: where the split between recalling and computing happens, and which training conditions create it.",
      built: ["retrieval-vs-computation", "https://github.com/Adya6714/retrieval-vs-computation"],
      links: [["Paper", "https://openreview.net/forum?id=d8w4gMVQ1w"], ["Project page", "https://adya6714.github.io/retrieval-vs-computation/"], ["Code", "https://github.com/Adya6714/retrieval-vs-computation"]] },
    { id: "r-vision", tag: "Vision", status: "Preprint", color: "violet",
      title: "Reading Without Looking",
      question: "When an OCR model says it is confident, is it actually looking at the page?",
      what: "Checks whether an OCR model's confidence comes from the page.",
      big: "0.99", caption: "average confidence on a blank page",
      did: "Trained a small OCR model from scratch for Indian scripts so every internal step could be inspected, then tested it with blank, noisy and scrambled pages, and checked the findings on a production OCR system.",
      found: ["Confidence tracked language patterns, not the image.", "Confidence that looked useful on familiar pages (AUROC 0.84) fell to near chance on new ones (0.57).", "Routing pages by confidence alone can send exactly the wrong pages through."],
      next: "Confidence scores that check whether the image actually supports the answer.",
      built: ["vlm-ocr-eval", "https://github.com/Adya6714/vlm-ocr-eval"],
      links: [["Project page", "https://adya6714.github.io/vlm-ocr-eval/"], ["Preprint", "https://adya6714.github.io/vlm-ocr-eval/paper/main.pdf"], ["Code", "https://github.com/Adya6714/vlm-ocr-eval"]] },
    { id: "r-markets", tag: "Markets", status: "Preprint", color: "mint",
      title: "Diffusion-Generated Volatility Surfaces for RL Hedging of NIFTY 50 Barrier Options",
      question: "Can AI-generated market data train a better hedging agent, and how much of the gain comes from the data versus the agent?",
      what: "Trains a hedging agent on AI-generated market data.",
      big: "60.1%", caption: "lower tail-risk hedging error than Black-Scholes",
      did: "Built 1,268 NIFTY 50 volatility surfaces from 912K+ option records, trained a diffusion model to generate new ones, and trained a reinforcement learning agent to hedge barrier options on them.",
      found: ["Generated surfaces had fewer pricing inconsistencies than real data (0.005 vs 0.009).", "The agent cut CVaR(95%) hedging error by 60.1% against Black-Scholes.", "A model-risk decomposition separates the gain from better data and from a better agent."],
      next: "Testing across market regimes and other indices.",
      built: ["ddpm-vol-hedging", "https://github.com/Adya6714/ddpm-vol-hedging"],
      links: [["Paper (PDF)", "https://github.com/Adya6714/ddpm-vol-hedging/blob/main/paper/Volatility_Surfaces_Research.pdf"], ["Code", "https://github.com/Adya6714/ddpm-vol-hedging"]] },
    { id: "r-quantum", tag: "Quantum", status: "Preprint", color: "sky",
      title: "Hybrid Quantum-Classical Paradigms for Nonlinear Dynamics, Machine Learning and Autonomous Systems",
      question: "Where can quantum and classical computing work together on problems neither handles well alone?",
      what: "Maps how quantum and classical computing can work together.",
      big: "6 topics", caption: "connected in one framework",
      did: "A survey that connects methods for simulating nonlinear systems on quantum hardware, quantum approaches to learning and control, and a comparison of hardware and energy efficiency.",
      found: ["Covers Carleman linearization, quantum Fokker-Planck embedding, variational algorithms for PDEs, quantum reinforcement learning and quantum game theory.", "Compares hardware platforms and energy efficiency in one place."],
      next: "Turning the survey's open problems into small experiments.",
      built: null,
      links: [["Paper (PDF)", "https://drive.google.com/file/d/1zwhnW2Nvl6I5myx556UoGED-1MKv9qt5/view?usp=sharing"]] }
  ],

  articles: [
    { id: "a-score", title: "The same score can hide different strategies", sub: "What happened when I changed only the names in a test", min: 4,
      links: [["Paper", "https://openreview.net/forum?id=d8w4gMVQ1w"], ["Project page", "https://adya6714.github.io/retrieval-vs-computation/"], ["Code", "https://github.com/Adya6714/retrieval-vs-computation"]],
      body: [
        "When two AI models get the same score on a test, it is tempting to say they are equally good at the task. I wanted to know whether that is true. So I tried something simple: I kept every problem exactly the same and changed only the surface, like the names of the people and things in it.",
        "## How I tested it",
        "I built three probes. The first rewrites a problem in ways that should not matter, such as new names and new wording. The second checks whether a model actually follows its own plan. The third measures how close a problem is to the kind of text a model has probably seen. I ran 219 problems across arithmetic, planning and optimisation on five models, about 20,000 calls in total, and every answer was checked by an exact verifier rather than by eye.",
        "## A perfect score disappeared",
        "o3-mini solved every weighted interval scheduling problem in its original form. After I renamed the entities, it solved none of them. The score went from 1.00 to 0.00. The problem had not changed at all.",
        "## The same change did not hit every model the same way",
        "On arithmetic, Gemini scored 0.909 on the original problems and 0.958 when I regenerated the numbers. When I changed only the names, it fell to 0.523. Across models, the same rename moved scores by very different amounts, left two models close to the floor, and even reversed direction between problem types. If every model were simply recalling memorised problems, I would expect the same kind of drop everywhere. It looks more like each model has its own habits.",
        "## Accepting a wrong step is not the same as being derailed",
        "Halfway through a solution, I injected a wrong intermediate value. The models that went along with it accepted it 88 to 100% of the time. But whether a model accepted the wrong value did not predict whether it got the final answer right. After the injection, accuracy stayed close to normal (Claude 52.5%, GPT-4o 50.8%, o3-mini 37.7%). Going along with a wrong step and being thrown off by it are two different things, and you have to measure them separately.",
        "## My own checks caught my own mistakes",
        "Along the way my verifier had bugs. I caught them by feeding it answers I knew were correct and making sure they scored as correct, before I trusted any result. If you measure models, you also have to measure your measuring stick.",
        "## What this does not show",
        "Even with all three probes, 61.6% of problems stayed ambiguous under strict thresholds. So the probes work better as calibration points than as a verdict on any single problem.",
        "## Why it matters",
        "If you pick a model by its score, you are betting that it will behave the same way on problems that look a little different. This work suggests that bet is riskier than the score implies, and that the risk differs from model to model. The next step is to look inside the models and find where recalling and computing split."
      ] },
    { id: "a-ocr", title: "My OCR model was 90% confident, and almost never right", sub: "Why a high confidence score does not mean the model looked at the page", min: 4,
      links: [["Project page", "https://adya6714.github.io/vlm-ocr-eval/"], ["Preprint", "https://adya6714.github.io/vlm-ocr-eval/paper/main.pdf"], ["Code", "https://github.com/Adya6714/vlm-ocr-eval"]],
      body: [
        "Document AI systems often use a confidence score to decide which pages to trust and which to send to a person. That only works if a high score means the model actually read the page. I wanted to test that for Indian scripts like Hindi and Bengali.",
        "## Why I trained my own model",
        "You cannot blank the image or switch off a layer inside a closed API. So I trained a small OCR model from scratch (about 20 million parameters) with real script shaping rendered by HarfBuzz. A small model I fully control is a measuring instrument. I could blank the page, add noise, scramble it, and even switch off the vision pathway to see what the model really depended on.",
        "## The first character gave it away",
        "At the first character of a line, no earlier text can help the model guess. There, it reported about 90% confidence, while the correct character had a probability of roughly 2 in 100 billion. Across 180 checks, the correct character was never its top choice.",
        "## A blank page looked as sure as a real one",
        "Average confidence was 0.994 on real text and 0.990 on a blank page. Noise and scrambled pages gave almost the same numbers. The score was reacting to how peaked the model's output was, which follows from language patterns, not to whether the image supported the text.",
        "## A good score on familiar lines did not last",
        "On lines similar to training data, confidence separated right answers from wrong ones reasonably well (AUROC 0.838). On held-out lines it dropped to about 0.57, close to a coin flip, and the calibration error was large (0.811). A meter that looks good in testing can be nearly useless on new pages.",
        "## Does it hold on a real system?",
        "I ran the same style of test against a production Indic OCR system. Its confidence moved by only 0.0027 across a 40-point gap in accuracy, and routing pages by confidence did worse than routing them at random.",
        "## What this does not show",
        "This is one small model, two scripts and a limited number of pages. It does not show that every OCR system is broken. It shows that confidence cannot be trusted by itself, and that you should test it with a blank page before you rely on it.",
        "## Why it matters",
        "A system that auto-accepts high-confidence pages would wave through exactly the pages it understands least. A better signal would check that the image actually supports the answer, which is where I want to take this next."
      ] }
  ],

  /* kind picks the thumbnail artwork */
  projects: [
    { id: "p-rvc", title: "Retrieval vs Computation", group: "Research code", kind: "bars", featured: true,
      line: "A measurement toolkit that tells whether an AI model reasoned or recalled.", chips: ["LLM evaluation", "Reasoning", "Robustness"],
      skills: ["Python", "LLM APIs", "Statistical testing", "Verifiers"],
      problem: "Benchmarks say whether an answer is right, not how the model got there. Two models with the same score can fail in very different ways once deployed.",
      built: ["Three probes: rewording and renaming, plan versus execution, and closeness to training data.", "219 problems across arithmetic, planning and optimisation, with exact checkers for every answer.", "A reproducible pipeline where raw runs, metrics, tables and tests regenerate from code."],
      impact: "Gives teams a way to judge which models to trust on unseen problems. Paper at CAISc 2026, and phase one of a four-paper program.",
      site: "https://adya6714.github.io/retrieval-vs-computation/", code: "https://github.com/Adya6714/retrieval-vs-computation", paper: "https://openreview.net/forum?id=d8w4gMVQ1w" },
    { id: "p-ocr", title: "Reading Without Looking", group: "Research code", kind: "scan", featured: true,
      line: "A from-scratch Indic OCR model that shows confidence can stay high with no image.", chips: ["Vision-language", "Calibration", "Indic OCR"],
      skills: ["PyTorch", "OCR", "HarfBuzz", "Calibration"],
      problem: "Document systems auto-accept pages with high confidence. That only works if confidence tracks what the model actually sees.",
      built: ["Grapheme-level scoring and a renderer that produces real Indic script shaping.", "A small OCR model trained from scratch so every step can be inspected.", "Blank, noise and scrambled controls, plus a transfer test on a production OCR API."],
      impact: "Shows high confidence can mean the image barely mattered, so routing pages on it alone can fail.",
      site: "https://adya6714.github.io/vlm-ocr-eval/", code: "https://github.com/Adya6714/vlm-ocr-eval", paper: "https://adya6714.github.io/vlm-ocr-eval/paper/main.pdf" },
    { id: "p-ddpm", title: "Synthetic Volatility Surfaces for Hedging", group: "Research code", kind: "surface", featured: true,
      line: "AI-generated NIFTY 50 market data used to train a hedging agent.", chips: ["Diffusion models", "Reinforcement learning", "Quant"],
      skills: ["PyTorch", "DDPM", "PPO", "Options pricing"],
      problem: "Hedging exotic options with reinforcement learning needs far more scenarios than history provides.",
      built: ["1,268 NIFTY 50 volatility surfaces from 912K+ option records.", "A diffusion model that generates new surfaces with fewer pricing inconsistencies.", "A PPO hedging agent for barrier options, compared with Black-Scholes."],
      impact: "60.1% lower tail-risk hedging error than Black-Scholes, with a decomposition of data versus agent.",
      code: "https://github.com/Adya6714/ddpm-vol-hedging", paper: "https://github.com/Adya6714/ddpm-vol-hedging/blob/main/paper/Volatility_Surfaces_Research.pdf" },
    { id: "p-mesh", title: "OmniMesh", group: "AI systems", kind: "mesh", featured: true,
      line: "Offline disaster triage: phones relay emergencies when the internet is down.", chips: ["Android", "Multi-agent", "Offline-first"],
      skills: ["Kotlin", "Jetpack Compose", "Firebase", "Gemini", "P2P networking"],
      problem: "In disasters, internet and mobile networks fail first, exactly when responders need to coordinate.",
      built: ["An Android app where phones relay emergencies by severity over a peer-to-peer mesh.", "A command dashboard on the web with a live demo.", "AI that drafts the dispatch plan once data reaches the command plane."],
      impact: "Keeps triage and communication working when normal infrastructure is down. Built for the AMD Developer Hackathon and entered in the Google Solution Challenge.",
      site: "https://omnimesh-command.web.app", code: "https://github.com/Adya6714/OmniMesh" },
    { id: "p-fs360", title: "FraudScope360", group: "AI systems", kind: "graph", featured: true,
      line: "Five fraud detectors fused into one risk score. Citi national winner.", chips: ["Graph ML", "Anomaly detection", "FastAPI"],
      skills: ["Isolation Forest", "Node2Vec", "DBSCAN", "Kafka", "FastAPI", "Streamlit"],
      problem: "Fraud rarely looks suspicious one account at a time. It shows up in the connections between accounts, identities and behaviour.",
      built: ["Five detectors: anomalies, sudden behaviour changes, fraud networks, identity clusters and text.", "A fusion step that turns them into one risk score.", "A FastAPI service and a Streamlit dashboard."],
      impact: "National winner of the Citi Bank Campus Innovation Challenge.",
      code: "https://github.com/Adya6714/FraudScope360" },
    { id: "p-fsense", title: "FraudSense AI", group: "AI systems", kind: "shield", featured: true,
      line: "Catches AI-assisted cheating in interviews using several independent signals.", chips: ["LLM detection", "Keystroke biometrics", "NLP"],
      skills: ["DetectGPT", "GLTR", "Embeddings", "Streamlit"],
      problem: "Candidates can read answers written by an AI during a live interview, and any single detector is easy to fool.",
      built: ["Writing-style signals (DetectGPT, GLTR), typing behaviour, honeypot questions and embedding similarity.", "A rule that needs at least three independent signal types before anyone is flagged."],
      impact: "Fewer false alarms against honest candidates, and a result that is hard to game.",
      code: "https://github.com/Adya6714/FraudSense-AI" },
    { id: "p-pulse", title: "ContentPulse", group: "AI systems", kind: "pulse",
      line: "Upload a social post as text, image or PDF and get structured engagement feedback.", chips: ["Gemini API", "OCR", "Full stack"],
      skills: ["FastAPI", "React", "Gemini", "OCR", "Vercel", "Railway"],
      problem: "Creators get vague feedback on what makes a post work.",
      built: ["Text, image (OCR) and PDF inputs.", "Strict JSON output from Gemini for clean rendering.", "A deployed frontend and API with documentation."],
      impact: "A production-deployed tool that turns a post into concrete suggestions.",
      site: "https://social-analyzer-six.vercel.app/", code: "https://github.com/Adya6714/social-analyzer" },
    { id: "p-pdf", title: "PDF Extractor", group: "AI systems", kind: "doc",
      line: "Pulls out a PDF's structure, then finds the sections that matter to a given reader.", chips: ["Document AI", "NLP", "Docker"],
      skills: ["Python", "Semantic ranking", "Docker"],
      problem: "Long PDFs hide the few sections a particular reader actually needs.",
      built: ["Outline extraction with heading hierarchy.", "Persona-based selection of the most relevant sections."],
      impact: "Turns a long document into a short, relevant reading list.",
      code: "https://github.com/Adya6714/pdf_extractor" },
    { id: "p-grid", title: "GridLock 2.0: Traffic Demand", group: "Forecasting and data", kind: "map",
      line: "Forecasts traffic demand for every map cell and 15-minute slot. Scored 87.9.", chips: ["Forecasting", "Ensembling", "Gradient boosting"],
      skills: ["Spatiotemporal modelling", "Gradient boosting", "Python"],
      problem: "Predict demand for tens of thousands of map cells and time slots.",
      built: ["A four-way ensemble with blend weights per road type.", "A fully reproducible pipeline that runs on a CPU in minutes."],
      impact: "Score of 87.9 (100 x R squared) from competition data only, with no outside data.",
      code: "https://github.com/Adya6714/traffic-prediction" },
    { id: "p-route", title: "RouteCast360", group: "Forecasting and data", kind: "route",
      line: "Forecasts final seat counts on intercity bus routes.", chips: ["CatBoost", "Time series", "Feature engineering"],
      skills: ["CatBoost", "Target encoding", "GroupKFold"],
      problem: "Operators need to know how many seats a route will sell before departure.",
      built: ["Booking and search signals plus calendar context.", "Grouped cross-validation by day of year."],
      impact: "A reliable forecast built from transactional signals.",
      code: "https://github.com/Adya6714/RouteCast360" },
    { id: "p-price", title: "SmartPricing360", group: "Forecasting and data", kind: "tag",
      line: "A pricing model project.", chips: ["Machine learning", "Pricing", "Notebook"],
      skills: ["Python", "Scikit-learn"],
      problem: "Choosing prices that balance demand and margin.", built: ["A modelling notebook."], impact: "An end-to-end pricing exercise.",
      code: "https://github.com/Adya6714/smart-pricing360" },
    { id: "p-ganga", title: "Ganga MRV", group: "Forecasting and data", kind: "leaf",
      line: "Checks whether soil data supports a carbon-removal credit.", chips: ["Data analysis", "Statistics", "Verification"],
      skills: ["Python", "Statistics", "Data visualisation"],
      problem: "A carbon credit is only worth something if the measurements behind it hold up.",
      built: ["A complete measure, report and verify pipeline.", "A teaching book that explains every step.", "A live dashboard walkthrough."],
      impact: "A verified answer to whether the data supports the claim.",
      site: "https://site-eight-khaki-34.vercel.app", code: "https://github.com/Adya6714/ganga-mrv" },
    { id: "p-dim", title: "Data in Motion", group: "Products and platforms", kind: "flow",
      line: "Chooses the right cloud storage tier for each file and moves it automatically.", chips: ["Optimisation", "Kafka", "Cloud"],
      skills: ["MILP", "Scikit-learn", "Redpanda", "FastAPI", "Docker"],
      problem: "Storage tiers trade cost against speed, and the best placement changes as usage changes.",
      built: ["A mixed-integer program that chooses placement.", "A streaming pipeline that carries out migrations."],
      impact: "Turns storage placement into an optimisation instead of a manual decision.",
      code: "https://github.com/Adya6714/data-in-motion" },
    { id: "p-coin", title: "Meme Coin Aggregator", group: "Products and platforms", kind: "coin",
      line: "One real-time API for meme-coin data across exchanges.", chips: ["TypeScript", "WebSockets", "Caching"],
      skills: ["TypeScript", "WebSockets", "Caching", "REST"],
      problem: "Token data is scattered across exchanges and changes every second.",
      built: ["Aggregation, deduplication and sorting.", "Live updates over WebSockets."], impact: "A single clean feed for downstream apps.",
      code: "https://github.com/Adya6714/meme-coin-aggregator" },
    { id: "p-ondc", title: "ONDC Food Platform", group: "Products and platforms", kind: "basket",
      line: "Connects farmers, restaurants and food banks to cut waste.", chips: ["Backend", "Demand forecasting", "Social impact"],
      skills: ["Python", "Flask", "Forecasting"],
      problem: "Surplus food and unmet demand exist side by side.", built: ["Users, inventory and demand prediction."], impact: "A starting point for matching supply with need.",
      code: "https://github.com/Adya6714/ONDC-Food-Platform" },
    { id: "p-wml", title: "WML: Who's Most Like", group: "Early work", kind: "game",
      line: "A party game: draw a word and tag the friend who fits it best.", chips: ["React", "Flask", "Fun"],
      skills: ["React", "Flask", "JavaScript"], problem: "A small, playful full-stack build.", built: ["Random words, a live leaderboard and friend profiles."], impact: "A finished, shareable app.",
      code: "https://github.com/Adya6714/WML" },
    { id: "p-psms", title: "PSMS", group: "Early work", kind: "board",
      line: "An early full-stack application.", chips: ["JavaScript", "Full stack"], skills: ["JavaScript"],
      problem: "Early full-stack practice.", built: ["A working web app."], impact: "Foundation for later builds.", code: "https://github.com/Adya6714/PSMS" },
    { id: "p-task", title: "Task Board", group: "Early work", kind: "board",
      line: "A task board web app.", chips: ["JavaScript", "Full stack"], skills: ["JavaScript"],
      problem: "Early full-stack practice.", built: ["A working task board."], impact: "Foundation for later builds.", code: "https://github.com/Adya6714/task-board-app" },
    { id: "p-atari", title: "Atari RL Agent", group: "Early work", kind: "game",
      line: "My first reinforcement learning project and a log of how I learned ML.", chips: ["Reinforcement learning", "Python", "Notes"],
      skills: ["Python", "Reinforcement learning"], problem: "Learning RL by building an agent.", built: ["An Atari-playing agent and learning notes."], impact: "Where my ML journey started.",
      code: "https://github.com/Adya6714/Atari-game-RL-Agent" }
  ],

  /* stops on the path: flags in front of the arches in the painting. bx,by = base of the flag pole in map pixels */
  path: [
    { id: "j-bits", flag: "BITS Pilani", tag: "EEE, class of 2026", sub: "Education", when: "2022 to 2026", bx: 140, by: 614, rev: false, color: "#8fd0ff",
      line: "Where it started: electrical engineering fundamentals, and where I found research.",
      bullets: ["B.E. in Electrical and Electronics Engineering.", "Where I found research: papers, experiments and building from scratch.", "Combined hardware thinking with machine learning and quantitative work."],
      impact: [["B.E.", "Electrical and Electronics"], ["2026", "Graduated"]], skills: ["Python", "Machine learning"] },
    { id: "j-kat", flag: "Khageshvara", tag: "Drone tech startup", sub: "Product Development Lead and ML Intern", when: "May to Oct 2023", bx: 165, by: 538, rev: false, color: "#7fe3c8",
      line: "Drone vision that spots people in real time.",
      bullets: ["Built CNN vision pipelines for real-time human detection from drones.", "Built the financial model and pitch behind a successful DST funding round."],
      impact: [["Real time", "person detection from aerial video"], ["Funded", "DST funding secured"]], skills: ["Computer vision", "CNNs", "OpenCV"] },
    { id: "j-grasim", flag: "Grasim", tag: "Aditya Birla Group", sub: "Research Engineer, Aditya Birla Group", when: "May to Jul 2024", bx: 724, by: 649, rev: true, color: "#ffcf86",
      line: "Safer railway tracks using sensors and simulations.",
      bullets: ["Designed 20+ PLC railway simulations for autonomous control and safety validation.", "Built infrared and IoT sensor networks for real-time track monitoring."],
      impact: [["98%", "trespassing detection accuracy"], ["20+", "railway simulations"]], skills: ["IoT", "PLC", "Sensors"] },
    { id: "j-fidel", flag: "FidelFolio", tag: "Quant investments", sub: "Quant Investment Analyst", when: "May to Jun 2025", bx: 643, by: 499, rev: false, color: "#b9a6ff",
      line: "Portfolio research that raised risk-adjusted returns.",
      bullets: ["Built a research workflow for portfolio analytics and Sharpe evaluation.", "Used genetic algorithms and Bayesian optimisation for risk-aware portfolios.", "Analysed 24 factors across 200+ portfolios."],
      impact: [["+42%", "Sharpe ratio"], ["90%", "faster research workflow"]], skills: ["Portfolio optimisation", "Factor models", "Bayesian optimisation"] },
    { id: "j-nurix", flag: "Nurix AI", tag: "Production speech AI", sub: "ML Engineering Intern", when: "Jul to Dec 2025", bx: 602, by: 357, rev: false, color: "#72f1df",
      line: "Speech AI running in production.",
      bullets: ["Built and deployed a TinyBERT voicemail detector with backend integration.", "Designed a word-error correction pipeline using Word2Vec, phonetic normalisation and LLM scoring.", "Improved real-time turn-end detection in a transformer speech-to-text pipeline."],
      impact: [["95%", "voicemail detection precision"], ["40%", "fewer word errors"]], skills: ["Transformers", "Speech", "Deployment", "NLP"] }
  ],

  skills: [
    ["LLMs and NLP", ["PyTorch", "Transformers", "LLM evaluation", "Probing and ablation", "LangChain", "Gemini API"]],
    ["Vision and documents", ["OpenCV", "OCR", "CNNs", "Document AI"]],
    ["Generative and RL", ["Diffusion models", "PPO", "vLLM"]],
    ["Classical ML", ["XGBoost", "CatBoost", "scikit-learn", "Graph ML", "Anomaly detection"]],
    ["Systems", ["Python", "FastAPI", "Docker", "Kafka", "AWS", "GCP", "Firebase", "SQL", "TypeScript", "Kotlin"]],
    ["Quant", ["Portfolio optimisation", "Volatility modelling", "CVaR", "Backtesting"]]
  ],

  shelf: {
    study: { title: "AI/ML Chapters Module", status: "Writing in progress", blurb: "My own chapter notes, derivations and experiments while I learn ML properly. I keep adding to it, and you are welcome to read along.", chapters: [] },
    reading: [
      { id: "attn", title: "Attention Is All You Need", by: "Vaswani et al.", type: "Paper", tags: ["transformers", "ml"], finished: "2024", takeaway: "The paper that made me stop treating sequence models as RNNs with extras. Once attention is the whole architecture, a lot of later LLM behaviour starts to look inevitable.", rating: 5, recommend: true, url: "https://arxiv.org/abs/1706.03762" },
      { id: "ddpm", title: "Denoising Diffusion Probabilistic Models", by: "Ho, Jain, Abbeel", type: "Paper", tags: ["generative", "ml"], finished: "2025", takeaway: "Diffusion clicked for me when I treated noise schedules as the product, not the side detail. That framing is what I carried into generating volatility surfaces.", rating: 5, recommend: true, url: "https://arxiv.org/abs/2006.11239" },
      { id: "sutton", title: "Reinforcement Learning: An Introduction", by: "Sutton and Barto", type: "Book", tags: ["rl", "ml"], finished: "2025", takeaway: "Still the clearest map of what an agent is actually optimising. I go back to it whenever a hedging or triage demo starts hiding the reward definition.", rating: 5, recommend: true, url: "http://incompleteideas.net/book/the-book.html" },
      { id: "weng", title: "What are diffusion models?", by: "Lilian Weng", type: "Blog", tags: ["generative", "ml"], finished: "2025", takeaway: "Best short bridge from the DDPM math to something I could implement without getting lost in notation.", rating: 4, recommend: true, url: "https://lilianweng.github.io/posts/2021-07-11-diffusion-models/" },
      { id: "circuits", title: "A Mathematical Framework for Transformer Circuits", by: "Elhage et al.", type: "Paper", tags: ["interpretability", "ml"], finished: "2025", takeaway: "Gave me language for asking where a behaviour lives, which is the next step after my retrieval-versus-computation probes.", rating: 4, recommend: true, url: "https://transformer-circuits.pub/2021/framework/index.html" },
      { id: "neet", title: "NeetCode problem list", by: "NeetCode / LeetCode", type: "Course", tags: ["practice", "algorithms"], finished: "Ongoing", takeaway: "The DSA list I work through for interview prep.", rating: 5, recommend: false, url: "https://leetcode.com/problem-list/plakya4j/" },
      { id: "sysgh", title: "System Design course", by: "Karan Pratap Singh", type: "Course", tags: ["system-design"], finished: "Ongoing", takeaway: "Clear written system design notes I return to before interviews.", rating: 4, recommend: true, url: "https://www.karanpratapsingh.com/courses/system-design" },
      { id: "mlsys", title: "ML System Design", by: "YouTube", type: "Course", tags: ["ml", "system-design"], finished: "Ongoing", takeaway: "Loose playlist of ML system design walkthroughs. Useful for breadth, not a single standout resource.", rating: 3, recommend: false, url: "https://www.youtube.com/results?search_query=ml+system+design" },
      { id: "leet", title: "LeetCode profile", by: "LeetCode", type: "Course", tags: ["practice", "algorithms"], finished: "Ongoing", takeaway: "My public problem-solving profile.", rating: 4, recommend: false, url: "https://leetcode.com/u/adyasrivastava" }
    ],
    currently: [{ title: "AI/ML Chapters Module", by: "My notes", note: "Writing and revising chapters as I go." }],
    videos: [
      { id: "v-tm", title: "System Design Interview: Design Ticketmaster", by: "Hello Interview · Ex-Meta Staff", len: "59 min", videoId: "fhdPyoO6aXI", why: "A full Ticketmaster walkthrough the way a staff interviewer expects it." },
      { id: "v-agent", title: "AI Agent System Design in 19 Min", by: "YouTube", len: "19 min", videoId: "CyLYY_xb5bQ", why: "RAG, vector databases, evals and function calling in one pass." },
      { id: "v-reason", title: "Reasoning ML Models", by: "YouTube", len: "Watch", videoId: "Kh9mqTzjuEQ", why: "How reasoning models think step by step." }
    ],
    beyond: [
      { title: "Meraki", line: "Poems and short stories. An alleyway to sonder.", url: "https://srivastavadya.wixsite.com/meraki14", label: "Read on Meraki" },
      { title: "Case studies", line: "Consulting, product and business write-ups.", id: "cases", label: "See case studies" }
    ]
  },

  cases: [
    { t: "SBI Life - IdeationX 2.0", type: "Case study", line: "Insurance innovation for Gen Z, underserved customers, and everyday financial planning.", url: "assets/case-studies/sbi-life-ideationx-2.pdf" },
    { t: "Kshana - Your Health at Your Fingertips", type: "Pitch deck", line: "Unified medical records across hospitals, diagnostics, wearables and insurance.", url: "assets/case-studies/kshana-health-at-your-fingertips.pdf" },
    { t: "Zepto Café - Quick-Commerce Strategy", type: "Case study", line: "Private-label café strategy, hyperlocal infra, unit economics and growth bets.", url: "assets/case-studies/zepto-cafe-quick-commerce-strategy.pdf" },
    { t: "Quick Commerce - Market & Growth Strategy", type: "Case study", line: "India’s Q-commerce market: dark stores, behaviour, bundling and SKU design.", url: "assets/case-studies/zepto-cafe-quick-commerce-strategy.pdf" },
    { t: "AI-Powered Citizen Services - EY Techathon 5.0", type: "Case study", line: "Scheme eligibility, DigiLocker, multilingual AI help and grievance tracking.", url: "assets/case-studies/ai-powered-citizen-services-ey-techathon.pdf" },
    { t: "E-Waste Management - Holistic Recycling Ecosystem", type: "Case study", line: "Collection, tracking, partnerships and blockchain traceability for e-waste.", url: "assets/case-studies/e-waste-management-recycling-ecosystem.pdf" },
    { t: "Cloud Computing in Healthcare", type: "Case study", line: "Cloud-first health records, telemedicine and clinical decision support in India.", url: "assets/case-studies/cloud-computing-in-healthcare.pdf" },
    { t: "Indian Financial System - Marxian Analysis", type: "Assignment", line: "Banking, credit, NPAs and exclusion through a Marxian lens.", url: "assets/case-studies/indian-financial-system-marxian-analysis.pdf" },
    { t: "Parag Milk Foods - Equity & Portfolio Analysis", type: "Equity research", line: "Price, ratios and portfolio work with a cautious / avoid recommendation.", url: "assets/case-studies/parag-milk-foods-equity-portfolio-analysis.xlsx" },
    { t: "Indian Hemp Market - Market Entry Strategy", type: "Case study", line: "Market sizing, value chain, risks and entry paths for hemp in India.", url: "assets/case-studies/indian-hemp-market-entry-strategy.pdf" }
  ],

  suggest: {
    title: "Drop me a card",
    blurb: "Ideas I should explore, papers I should read, a hackathon you want a teammate for, or anything you think I should know. Anonymous is fine.",
    placeholder: "A suggestion, a resource, a hackathon idea, or just hello",
    types: ["Suggestion", "Resource", "Hackathon", "Opportunity", "Just hello"],
    thanks: ["Got it. Thank you for taking the time.", "Your card made it to me. I really appreciate it.", "Received. I will read this properly.", "Thank you. This kind of note makes my day."]
  },

  koi: { thanks: ["Thank you!", "Yum!", "Delicious", "More, please", "You are kind", "Best snack ever", "Splash!", "Thanks, friend"] },

  interview: {
    intro: "Hi, I am the guardian of this river. Interview Adya through me: her research, internships, projects, skills, or what she is looking for next. I answer only from her own notes and papers.",
    tracks: ["Start here", "Projects", "Research", "Behavioural", "Hard questions"],
    fallback: "I do not have that in Adya's notes. You can email her at srivastavadya@gmail.com, or try one of the questions below.",
    qs: [
      { id: "me", track: "Start here", q: "Tell me about yourself.", para: ["introduce yourself", "who are you", "what do you do", "your background"],
        short: "I'm Adya, an engineer who enjoys building things from scratch and figuring out how they work. I'm drawn to AI and ML because it sits between research and engineering: asking whether something really works, then building it so it does.",
        long: "I graduated from BITS Pilani in 2026 in Electrical and Electronics Engineering. My work ranges from research on how language models reason and how vision models express confidence, to shipped speech systems, forecasting and fraud detection.", next: ["looking", "why-ml"] },
      { id: "looking", track: "Start here", q: "What are you looking for right now?", para: ["job", "open to jobs", "open to work", "role", "opportunities", "hiring", "available", "next step"],
        short: "Opportunities where I can work closely with interesting problems in AI/ML, research and engineering, with people who are building and experimenting.",
        long: "I'm also happy to talk about hackathons, papers I should read, or a different way of looking at the field. If you have something in mind, the Drop me a card box at the end of the site is the easiest way to reach me.", next: ["hack", "re"] },
      { id: "why-ml", track: "Start here", q: "Why AI and ML?", para: ["why machine learning", "what drew you to ai", "motivation"],
        short: "Because it combines research and engineering. Research lets me chase questions without obvious answers, and engineering lets me build the answer.",
        long: "AI and ML sit at an exciting intersection of the two for me, and they keep me moving between papers, experiments and systems.", next: ["scratch", "re"] },
      { id: "scratch", track: "Start here", q: "Why do you like building things from scratch?", para: ["from scratch", "build yourself", "learning by building"],
        short: "Starting from a blank page forces me to understand each part. I learn what I need, build a first version, break it, then work out why it behaved that way.",
        long: "Training my OCR model from scratch is a good example. Because I controlled every part, I could blank the image or switch off the vision pathway and see what the model really depended on.", next: ["ocr", "convincing"] },
      { id: "re", track: "Start here", q: "Is your research different from your engineering work?", para: ["research versus engineering", "engineer or researcher", "difference research engineering"],
        short: "They feed each other. Research is where I ask whether something really works and why. Engineering is where I make it work for someone.",
        long: "Most of my projects have a bit of both. My evaluation papers come with open code and reproducible pipelines, and my shipped systems come with measured results.", next: ["rvc", "nurix"] },
      { id: "hack", track: "Start here", q: "Do you take part in hackathons?", para: ["hackathon", "competitions", "teammate"],
        short: "Yes. FraudScope360 won the national round of the Citi Bank Campus Innovation Challenge, and I built OmniMesh for the AMD Developer Hackathon and the Google Solution Challenge.",
        long: "If you have a hackathon in mind and want a teammate, or know a resource worth my time, drop me a card.", next: ["mesh", "fraudscope"] },

      { id: "rvc", track: "Projects", q: "What is Retrieval vs Computation?", para: ["same score different strategy", "caisc paper", "reasoning paper", "retrieve or compute", "recall or reason"],
        short: "A way to tell whether an AI model worked a problem out or recalled something similar it had seen. Benchmark scores cannot separate the two, so I built probes that can.",
        long: "Three probes: rename and reword problems, check that a model follows its own plan, and measure closeness to training data. I ran 219 problems on five models. Matching scores hid big differences: o3-mini went from 1.00 to 0.00 on a scheduling task after only the names changed.", next: ["artifacts", "wrong"] },
      { id: "ocr", track: "Projects", q: "What is Reading Without Looking?", para: ["ocr confidence", "indic ocr", "own ocr model", "train your own ocr", "why did you build your own ocr model", "ocr from scratch", "blank page", "vision language", "confidence calibration"],
        short: "A study of whether OCR confidence comes from the page. I trained a small model from scratch for Hindi and Bengali and found it stayed about as confident on a blank page as on real text.",
        long: "At the first character, it reported about 90% confidence while the correct character had roughly 2 in 100 billion probability. Confidence that separated right from wrong on familiar lines (AUROC 0.84) fell to about 0.57 on new ones.", next: ["scratch", "selfcritique"] },
      { id: "ddpm", track: "Projects", q: "Why use diffusion models for market data?", para: ["volatility surfaces", "hedging agent", "ddpm", "reinforcement learning hedging", "nifty"],
        short: "A hedging agent needs far more market scenarios than history provides. A diffusion model can generate realistic new volatility surfaces to train on.",
        long: "I built 1,268 NIFTY 50 surfaces from 912K+ option records, generated new ones, and trained a PPO agent to hedge barrier options. It cut tail-risk hedging error (CVaR 95%) by 60.1% against Black-Scholes, and I separate how much came from the data versus the agent.", next: ["convincing", "compute"] },
      { id: "mesh", track: "Projects", q: "Why did you build OmniMesh?", para: ["offline disaster", "mesh network", "omnimesh", "triage"],
        short: "In disasters, internet and mobile networks fail first, exactly when responders need to coordinate. OmniMesh keeps triage working offline.",
        long: "Android phones relay emergencies by severity peer to peer, and once data reaches a command dashboard, AI drafts the dispatch plan. There is a live demo and an Android build.", next: ["hack", "fraudscope"] },
      { id: "fraudscope", track: "Projects", q: "How does FraudScope360 work?", para: ["fraud detection", "citi", "fraud rings", "graph ml"],
        short: "Five independent detectors (anomalies, sudden behaviour changes, fraud networks, identity clusters and text) are fused into one risk score.",
        long: "It uses Isolation Forest, change-point detection, Node2Vec on the transaction network, DBSCAN with fuzzy matching, and a text model, served through FastAPI with a Streamlit dashboard. It won the national round of the Citi Bank Campus Innovation Challenge.", next: ["fraudsense", "hack"] },
      { id: "fraudsense", track: "Projects", q: "How do you avoid flagging honest candidates in FraudSense?", para: ["false positives", "interview fraud", "ai cheating detection"],
        short: "No single signal can flag anyone. At least three independent signal types must agree before a flag is raised.",
        long: "The signals are writing style (DetectGPT, GLTR), typing behaviour, honeypot questions and embedding similarity.", next: ["fraudscope", "convincing"] },
      { id: "nurix", track: "Projects", q: "What did you ship at Nurix?", para: ["internship", "speech", "voicemail", "production ml", "work experience"],
        short: "Production speech and NLP: a TinyBERT voicemail detector with 95% precision, a word-error correction pipeline that cut errors by 40%, and better real-time turn-end detection.",
        long: "The correction pipeline used Word2Vec, phonetic normalisation and LLM scoring. I worked on backend integration and deployment as well as the models.", next: ["re", "grid"] },
      { id: "grid", track: "Projects", q: "Tell me about GridLock 2.0.", para: ["traffic prediction", "forecasting", "ensemble"],
        short: "A traffic demand forecasting project that scored 87.9 using a four-way ensemble with blend weights per road type, built only from competition data.",
        long: "The whole pipeline is reproducible from the repository and runs on a CPU in a few minutes.", next: ["nurix", "convincing"] },

      { id: "questions", track: "Research", q: "How do you come up with research questions?", para: ["research ideas", "research process", "how do you do research", "choose a question", "where do ideas come from"],
        short: "I start where a number feels too convenient. A benchmark score, a confidence value, a hedging result: I ask what is hiding behind it.",
        long: "Both of my evaluation papers began that way. They ask whether the score means what people assume it means.", next: ["convincing", "now"] },
      { id: "convincing", track: "Research", q: "How do you know an experiment is convincing?", para: ["rigour", "validation", "validate results", "check results", "trust results", "statistical testing"],
        short: "I check the instrument first, then the result. Verifiers get known-correct answers before I trust them, and findings are tested on held-out data and, where possible, on a real system.",
        long: "In the OCR work I pre-registered the statistics for the transfer test. In the reasoning work I used exact answer checkers and significance testing.", next: ["artifacts", "failure"] },
      { id: "artifacts", track: "Research", q: "Could your probes create the effect themselves?", para: ["confounders", "artifacts", "benchmark artifact", "distribution shift"],
        short: "That is the main risk, so I built checks around it: gold-in, gold-out tests for every verifier, and several different surface changes instead of one.",
        long: "Regenerating numbers barely hurt Gemini while renaming entities did, which points to something about the names rather than a general disruption. I also report that 61.6% of instances stay ambiguous, so the probes are calibration points rather than a verdict.", next: ["wrong", "selfcritique"] },
      { id: "now", track: "Research", q: "What are you researching now?", para: ["current work", "next paper", "future work"],
        short: "Looking inside models: where the split between recalling and computing happens, and which training conditions create it. Also confidence scores that check whether the image supports the answer.",
        long: "The reasoning paper is the first of a four-paper program on this question.", next: ["compute", "looking"] },

      { id: "wrong", track: "Behavioural", q: "Tell me about a hypothesis that turned out wrong.", para: ["hypothesis wrong", "surprised", "changed your mind"],
        short: "I expected three probes to label every problem as retrieved or computed. Under strict thresholds, 61.6% of problems stayed ambiguous.",
        long: "So I reframed the labels as calibration points and made the paper about what behavioural probes can and cannot show.", next: ["failure", "artifacts"] },
      { id: "failure", track: "Behavioural", q: "Tell me about something that went wrong.", para: ["failure", "mistake", "bug"],
        short: "My own verifiers had bugs. I found them by feeding them answers I knew were correct and checking that they scored as correct.",
        long: "Fixing them changed some results, which is why I now validate the measuring stick before I trust any number it produces.", next: ["convincing", "wrong"] },
      { id: "new", track: "Behavioural", q: "How do you learn something completely new?", para: ["learning", "new topic", "pick up quickly"],
        short: "I build a rough first version early, break it, and read what I need to understand why it broke.",
        long: "That is how I went from reading about OCR calibration to training my own model, and from reading about diffusion models to generating volatility surfaces.", next: ["scratch", "weak"] },
      { id: "weak", track: "Behavioural", q: "What are you trying to get better at?", para: ["improve", "growth", "weakness"],
        short: "Going from behaviour to mechanism: moving from measuring what models do to explaining why, with interpretability tools and controlled training runs.",
        long: "That is the direction of the next papers in my research program.", next: ["now", "compute"] },

      { id: "resume-weak", track: "Hard questions", q: "What is easy to misunderstand on your resume?", para: ["resume weakness", "weakest part"],
        short: "That my internships are short. They are focused: each one produced a concrete, measured result, and my research shows depth over a longer stretch.",
        long: "If you want proof, the papers and code are public.", next: ["hire", "selfcritique"] },
      { id: "selfcritique", track: "Hard questions", q: "What would you challenge about your own research?", para: ["limitations", "criticism", "weaknesses of your work"],
        short: "Scale and scope. The OCR study uses one small model and two scripts, and the reasoning study is behavioural, so it cannot say where inside the model the split happens.",
        long: "I state those limits in both papers and they set up the next steps.", next: ["now", "compute"] },
      { id: "compute", track: "Hard questions", q: "What would you do with ten times the compute?", para: ["more gpus", "unlimited resources", "scale up"],
        short: "Run controlled training experiments and interpretability studies across model sizes to see where and why retrieval and computation separate.",
        long: "I would also repeat the OCR study across more scripts and larger models.", next: ["now", "weak"] },
      { id: "hire", track: "Hard questions", q: "Why should someone hire you?", para: ["why you", "strengths", "what do you bring"],
        short: "I can take a vague question, design the experiment, build the system, and tell you honestly what the result does and does not show.",
        long: "I have published research, shipped speech models in production, and built full systems like OmniMesh and FraudScope360.", next: ["looking", "re"] }
    ]
  }
};
